/**
 * Public @explodex/sdk authoring surface.
 * Renderer runtime is exported separately via `@explodex/sdk/runtime`.
 */

export { defineConfig } from "./define-config.ts";
export { definePlugin, isDefinedPlugin } from "./define-plugin.ts";
export {
  compareSemVer,
  currentSdkSatisfiesRange,
  evaluateSdkCompatibility,
  parseSemVer,
  satisfiesSdkRange,
  type ParsedSemVer,
  type SdkCompatibilityReason,
  type SdkCompatibilityVerdict,
} from "./compatibility.ts";
export { SDK_VERSION, type SdkVersion } from "./version.ts";

export type {
  ArtifactVersion,
  AnchorRect,
  BridgeApi,
  BridgeMessage,
  ButtonColor,
  ButtonOptions,
  ButtonSize,
  CheckboxFieldOptions,
  CodexApi,
  ComponentsApi,
  ComposerApi,
  DefinedPlugin,
  ExplodexConfig,
  ExplodexRuntimeApi,
  FieldRowOptions,
  FlagsApi,
  FlagsPropagateOptions,
  FormatApi,
  FormatDurationOptions,
  GlobalStateStorage,
  HttpApi,
  HttpRequestOptions,
  HttpResponse,
  InjectApi,
  LogLevel,
  MigrationContext,
  MountContext,
  MountOptions,
  MountStrategy,
  NavItemOptions,
  NumberFieldOptions,
  PanelOptions,
  PersistedStorage,
  PluginAssetHandle,
  PluginAssets,
  PluginApi,
  PluginCapabilityApi,
  PluginDefinition,
  PluginLifecycle,
  PluginLogger,
  PluginMigration,
  PluginOptionsHandlers,
  PluginOptionsRenderContext,
  PluginSetup,
  PluginSetupResult,
  PluginTeardown,
  PluginTrackedResources,
  PopoverOptions,
  PopoverSide,
  QueryApi,
  QueryClientApi,
  QueryRecord,
  RadioFieldOptions,
  ReasoningEffort,
  RepositionPopoverOptions,
  SectionOptions,
  SectionResult,
  SelectFieldOption,
  SelectFieldOptions,
  SettingsStorage,
  SidebarNavApi,
  SortableListItem,
  SortableListOptions,
  StorageApi,
  TextFieldOptions,
  ThreadConversation,
  TrackedEventListener,
  TrackedEventTarget,
  TrackedMountNode,
  TrackedObserver,
  UiApi,
  ZoneId,
} from "./types/index.ts";
export type { ExplodexRuntime } from "./runtime/public.ts";

export {
  DEFAULT_SETUP_TIMEOUT_MS,
  DEFAULT_TEARDOWN_TIMEOUT_MS,
} from "./lifecycle/constants.ts";
